---
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: kuard
  namespace: team-b
spec:
  routes:
    - match: /team-b
      prefixRewrite: "/"
      services:
        - name: kuard
          port: 8080
